export * from './Inicio.jsx'
export * from './Contacto.jsx'
export * from './Metodologias.jsx'
export * from './Programa.jsx'
export * from './Proyecto.jsx'
export * from './Footer.jsx'
export * from './Header.jsx'
export * from './SibreNosotrsos'